### ISSUE TITLE
Add javascript style to the code sections in README

### ISSUE THREAD

**Issue by DrJume** [aichholzer/attract#1]
You can add javascript style to the code sections by appending "js" after the beginning statement of a code block (```).

Without js style annotation:
```
const foo = "bar"
```
With:
```js
const foo = "bar"
```

**Comment by DrJume** [comment]
I am being a little OCD here :stuck_out_tongue:

**Comment by aichholzer** [comment]
I like it. Thank you.
Feel free to do a PR. 👍

**Comment by DrJume** [comment]
Please don't understand me wrong, but isn't this a little too small change for a PR? 😦

**Comment by aichholzer** [comment]
Nothing ever is, the community is built on blocks, which -in turn- are build of grains of sand. No sand, no block, no community. Every single contribution, no matter how small, is a contribution. Unless, of course, you don't want to contribute. ;)

**Comment by DrJume** [comment]
Wise words 👍 😄 
I merely thought you could quickly add the change by yourself 😜 
A PR _in my opinion_ would be rather too big for such a change in markdown.

**Comment by aichholzer** [comment]
Done!
👍
